name: Open Web Craft
favicon: null
layout_spectrum: 0.7245979842264205
typography_spectrum: 0.5847912176977843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8473654328845441
  lightness: 0.8092296728864312
  saturation: 0.10163489170372486
  rhythmicContrast: 0.19249006384052336
purpose: []
